name: Linters Check
on:
  pull_request:
    branches: [develop, main]
    paths: ['**.go', '**.cs']

jobs:
  lint-go:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: golangci-lint run ./...

  lint-csharp:
    name: Lint C-sharp Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet tool install -g dotnet-format
      - run: dotnet format --check --verbosity diagnostic
